### ISSUE TITLE
Refactor Redux State

### ISSUE THREAD

**Issue by adamshand** [thyme-to-code/thyme-is-money#3]
## clients
- active = [ { ‘Company 1’, …}  … ]
- selected = { business_name, … }
- xxxxx = [ { uninvoicedHours, uninvoicedAmount } ]
- loading

## tasks
- uninvoiced = [ {task_id, … }, … ]
- loading

## invoices
- all = [ { invoice_id, total, amount, … }, … ]
- current = { pdfUrl, invoiceJson, …}
- loading

## user
- auth0 = { id, token, email}

**Comment by dajabe** [comment]
Starting work on this today
